apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  project: default
  source:
    path: manifests
    repoURL: 'https://github.com/nkirchhoffer/nginx-clebard'
    targetRevision: HEAD
  destination:
    namespace: nginx
    server: 'https://kubernetes.default.svc'
